---
- hosts: lb
  sudo: yes
  gather_facts: no  
 

  tasks:

  - name: install haproxy
    yum: name=haproxy state=installed update_cache=yes

  - name: write our haproxy.cfg
    template: src=template/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=644 owner=root group=root
    notify: restart haproxy

  - name: start haproxy
    service: name=haproxy state=started

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted



- hosts: web1
  sudo: yes
  gather_facts: no


  tasks:
  - name: install epel-release
    yum: name=epel-release state=installed update_cache=yes

  - name: install nginx
    yum: name=nginx state=installed disable_gpg_check=yes validate_certs=no skip_broken=yes

  - name: write our index
    template: src=template/index.html dest=/usr/share/nginx/html/ mode=644 owner=root group=root
    notify: restart nginx

  - name: start nginx
    service: name=nginx state=started

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

- hosts: web2
  sudo: yes
  gather_facts: no


  tasks:
  - name: install epel-release
    yum: name=epel-release state=installed update_cache=yes

  - name: install nginx
    yum: name=nginx state=installed disable_gpg_check=yes validate_certs=no skip_broken=yes

  - name: write our index
    template: src=template/index2.html dest=/usr/share/nginx/html/index.html mode=644 owner=root group=root
    notify: restart nginx

  - name: start nginx
    service: name=nginx state=started

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted


